### ISSUE TITLE
Change DNS override to cloudflare

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/dotfiles#3]
Cloudflare provides a privacy-minded DNS resolver at 1.1.1.1 and 1.0.0.1, which can replace google’s 8.8.8.8 and 8.8.4.4

**Comment by Atavic** [comment]
Cloudflare isn't privacy-minded.

**Comment by JasonYao** [comment]
@Atavic [Cloudflare's privacy outline](https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/privacy-policy/) dictates a 24-hour period of logging before their logs are deleted, and any data that they do send is used for research purposes by APNIC, and is anonymized beforehand.

Moving from using google's default DNS of 8.8.8.8 and 8.8.4.4 where none of those privacy commitments are in place, and where google actively datamines the access logs to something like Cloudflare is definitely a no-brainer for increased privacy

**Comment by Atavic** [comment]
OK. Cloudflare is a big CDN and also they pretend to secure TLS. 

> The study measured interception from the vantage point of the Cloudflare CDN. Important results from the study found that about 5-10% of measured HTTPS connections were intercepted, and much of the software reduced the security of the end user in one way or another, with 54% of connections to Cloudflare becoming less secure. 

See: https://tlseminar.github.io/tls-interception/

The options to track millions of users is there IMHO

**Comment by JasonYao** [comment]
From https://1.1.1.1/, the DNS records to add in are:
- `1.1.1.1`
- `1.0.0.1`
- `2606:4700:4700::1111`
- `2606:4700:4700::1001`
